USE [master]
GO

/****** Object:  Database [EPAS_DEV3]    Script Date: 6/2/2020 11:18:14 AM ******/
CREATE DATABASE [EPAS_DEV3]
 CONTAINMENT = NONE

 ON  PRIMARY 
( NAME = N'EPAS_DEV3', FILENAME = N'D:\DBDATA\EPAS_DEV3.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EPAS_DEV3_log', FILENAME = N'D:\DBDATA\EPAS_DEV3_log.ldf' , SIZE = 25600KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

 COLLATE SQL_Latin1_General_CP1_CI_AS;  
GO
ALTER DATABASE [EPAS_DEV3] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EPAS_DEV3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO



ALTER DATABASE [EPAS_DEV3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET ARITHABORT OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EPAS_DEV3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EPAS_DEV3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EPAS_DEV3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EPAS_DEV3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET RECOVERY FULL 
GO

ALTER DATABASE [EPAS_DEV3] SET  MULTI_USER 
GO

ALTER DATABASE [EPAS_DEV3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EPAS_DEV3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EPAS_DEV3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EPAS_DEV3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EPAS_DEV3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EPAS_DEV3] SET QUERY_STORE = OFF
GO

USE [EPAS_DEV3]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [EPAS_DEV3] SET  READ_WRITE 
GO


