USE [master]
GO

/****** Object:  Database [EPAS]    Script Date: 6/2/2020 11:18:14 AM ******/
CREATE DATABASE [EPAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EPAS', FILENAME = N'D:\DBdata\EPAS.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EPAS_log', FILENAME = N'D:\DBdata\EPAS_log.ldf' , SIZE = 25600KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [EPAS] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EPAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EPAS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EPAS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EPAS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EPAS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EPAS] SET ARITHABORT OFF 
GO

ALTER DATABASE [EPAS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EPAS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EPAS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EPAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EPAS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EPAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EPAS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EPAS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EPAS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EPAS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EPAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EPAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EPAS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EPAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EPAS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EPAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EPAS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EPAS] SET RECOVERY FULL 
GO

ALTER DATABASE [EPAS] SET  MULTI_USER 
GO

ALTER DATABASE [EPAS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EPAS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EPAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EPAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EPAS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EPAS] SET QUERY_STORE = OFF
GO

USE [EPAS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [EPAS] SET  READ_WRITE 
GO


